// 노드 추가 모달
"use client"
import React from "react"
import styles from "../room-manage.module.css"

export default function NodeModal({
  show,
  onClose,
  nodeType,
  setNodeType,
  newNodeName,
  setNewNodeName,
  autoGeneratedName,
  onAdd,
}) {
  if (!show) return null

  return (
    <div className={styles["modal-overlay"]} onClick={onClose}>
      <div className={styles["node-modal-content"]} onClick={(e) => e.stopPropagation()}>
        {/* 제목 */}
        <div className={styles["node-modal-title"]}>
          <h3>노드 추가</h3>
          <div className={styles["title-underline"]}></div>
        </div>

        {/* 라디오 버튼 선택 */}
        <div className={styles["node-type-selection"]}>
          <label className={styles["radio-option"]}>
            <input
              type="radio"
              name="nodeType"
              value="stairs"
              checked={nodeType === "stairs"}
              onChange={(e) => setNodeType(e.target.value)}
            />
            <span className={styles["radio-custom"]}></span>
            계단
          </label>
          <label className={styles["radio-option"]}>
            <input
              type="radio"
              name="nodeType"
              value="normal"
              checked={nodeType === "normal"}
              onChange={(e) => setNodeType(e.target.value)}
            />
            <span className={styles["radio-custom"]}></span>
            노드
          </label>
        </div>

        {/* 자동 생성 노드명 표시 */}
        {nodeType === "normal" && (
          <div className={styles["auto-generated-name"]}>
            자동 생성 노드명: {autoGeneratedName}
          </div>
        )}

        {/* 입력 필드 */}
        {nodeType === "stairs" && (
          <div className={styles["input-fields"]}>
            <input
              type="text"
              value={newNodeName}
              onChange={(e) => setNewNodeName(e.target.value)}
              placeholder="노드명"
              className={styles["name-input"]}
            />
          </div>
        )}

        {/* 액션 버튼들 */}
        <div className={styles["modal-actions"]}>
          <button onClick={onClose} className={styles["cancel-btn"]}>
            취소
          </button>
          <button onClick={onAdd} className={styles["save-btn"]}>
            저장
          </button>
        </div>
      </div>
    </div>
  )
}

