// room-manage/edit
"use client"
import React, { useEffect, useRef, useState } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import styles from "../room-manage.module.css"

export default function RoomManageEditPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const building = searchParams.get("building") || ""
  const floor = searchParams.get("floor") || ""

  const [svgRaw, setSvgRaw] = useState("")
  const [svgViewBox, setSvgViewBox] = useState({ x: 0, y: 0, width: 400, height: 400 })
  const [edges, setEdges] = useState([])
  const [svgNodes, setSvgNodes] = useState([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [showNodeModal, setShowNodeModal] = useState(false)
  const [showCategoryModal, setShowCategoryModal] = useState(false)
  const [newNodeName, setNewNodeName] = useState("")
  const [newCategoryName, setNewCategoryName] = useState("")
  const [selectedCategory, setSelectedCategory] = useState("")
  const [nodeType, setNodeType] = useState("stairs") // "stairs" or "normal"
  const [autoGeneratedName, setAutoGeneratedName] = useState("")
  const [nodeCounter, setNodeCounter] = useState(1)
  const [pendingNodes, setPendingNodes] = useState([]) // 임시로 추가된 노드들
  const [isAddingMode, setIsAddingMode] = useState(false) // 노드 추가 모드
  const [pendingCategories, setPendingCategories] = useState([]) // 임시로 추가된 카테고리들
  const [isAddingCategoryMode, setIsAddingCategoryMode] = useState(false) // 카테고리 추가 모드

  const CANVAS_WIDTH = 1000
  const CANVAS_HEIGHT = 700
  const mapContainerRef = useRef(null)

  // 카테고리 한글-영어 매핑
  const categoryNameMap = {
    cafe: "카페",
    restaurant: "식당",
    convenience: "편의점",
    vending: "자판기",
    water_purifier: "정수기",
    printer: "프린터",
    lounge: "라운지",
    bank: "은행(atm)",
    fire_extinguisher: "소화기",
    gym: "헬스장",
    bookstore: "서점",
    post: "우체국",
  }

  // 미리 정의된 카테고리 목록 (한글 표시용)
  const categoryOptions = Object.values(categoryNameMap)

  // 자동 생성 노드명 업데이트
  useEffect(() => {
    if (nodeType === "normal") {
      setAutoGeneratedName(`b${nodeCounter}`)
    }
  }, [nodeType, nodeCounter])

  // 도면 클릭 핸들러
  const handleMapClick = (event) => {
    if (!isAddingMode && !isAddingCategoryMode) return

    // SVG 컨테이너의 실제 크기와 위치 가져오기
    const containerRect = mapContainerRef.current.getBoundingClientRect()
    const scale = Math.min(CANVAS_WIDTH / svgViewBox.width, CANVAS_HEIGHT / svgViewBox.height)
    const offsetX = (CANVAS_WIDTH - svgViewBox.width * scale) / 2
    const offsetY = (CANVAS_HEIGHT - svgViewBox.height * scale) / 2

    // 클릭한 위치를 SVG 좌표계로 변환 (더 간단한 방법)
    const relativeX = event.clientX - containerRect.left
    const relativeY = event.clientY - containerRect.top
    
    // SVG 컨테이너 내에서의 비율 계산
    const clickX = (relativeX / containerRect.width) * svgViewBox.width
    const clickY = (relativeY / containerRect.height) * svgViewBox.height

    // 🎯 클릭 좌표 변환 상세 로그
    console.log("=== 클릭 좌표 변환 ===")
    console.log("마우스 클릭 위치:", {
      clientX: event.clientX,
      clientY: event.clientY
    })
    console.log("컨테이너 정보:", {
      left: containerRect.left,
      top: containerRect.top,
      width: containerRect.width,
      height: containerRect.height
    })
    console.log("SVG 뷰박스:", svgViewBox)
    console.log("스케일 계산:", {
      scale,
      offsetX,
      offsetY
    })
    console.log("최종 변환된 좌표:", {
      clickX: clickX,
      clickY: clickY
    })
    console.log("=========================")

    if (isAddingMode) {
      // 노드 추가 모드
      const newNodeId = nodeType === "stairs" ? newNodeName.trim() : `b${nodeCounter}`
      const newNode = {
        id: `${building}@${floor}@${newNodeId}`,
        x: clickX,
        y: clickY,
        width: 8, // 기존 노드들과 비슷한 크기
        height: 8, // 기존 노드들과 비슷한 크기
        element: "circle",
        layer: "Navigation_Nodes",
        nodeType: nodeType,
        isPending: true
      }

      // 📍 새 노드 추가 로그
      console.log("=== 새 노드 추가 ===")
      console.log("노드 ID:", newNode.id)
      console.log("노드 좌표:", { x: newNode.x, y: newNode.y })
      console.log("노드 타입:", newNode.nodeType)
      console.log("노드 크기:", { width: newNode.width, height: newNode.height })
      console.log("===================")

      setPendingNodes(prev => [...prev, newNode])
      
      // 일반 노드인 경우 카운터 증가
      if (nodeType === "normal") {
        setNodeCounter(prev => prev + 1)
      }

      // 모달 닫기
      setShowNodeModal(false)
      setIsAddingMode(false)
    } else if (isAddingCategoryMode) {
      // 카테고리 추가 모드
      const englishCategoryName = Object.keys(categoryNameMap).find(
        key => categoryNameMap[key] === selectedCategory
      )
      
      const newCategory = {
        id: `${building}@${floor}@${englishCategoryName}`,
        x: clickX,
        y: clickY,
        width: 8,
        height: 8,
        element: "circle",
        layer: "Categories",
        categoryType: englishCategoryName,
        isPending: true
      }

      // 🏷️ 새 카테고리 추가 로그
      console.log("=== 새 카테고리 추가 ===")
      console.log("카테고리 ID:", newCategory.id)
      console.log("카테고리 좌표:", { x: newCategory.x, y: newCategory.y })
      console.log("카테고리 타입:", newCategory.categoryType)
      console.log("카테고리 크기:", { width: newCategory.width, height: newCategory.height })
      console.log("========================")

      setPendingCategories(prev => [...prev, newCategory])
      setShowCategoryModal(false)
      setIsAddingCategoryMode(false)
    }
  }

  function parseNodeInfo(fullId) {
    const parts = (fullId || "").split("@")
    if (parts.length < 3) return { building: "", floor: "", node: "" }
    return { building: parts[0], floor: parts[1], node: parts[2] }
  }

  const handleAddNode = () => {
    // 계단인 경우 노드 이름이 필요
    if (nodeType === "stairs" && !newNodeName.trim()) {
      alert("노드명을 입력해주세요.")
      return
    }
    
    // 노드 추가 모드로 전환
    setIsAddingMode(true)
    setShowNodeModal(false)
    alert("도면에서 노드를 추가할 위치를 클릭해주세요.")
  }

  // 수정 완료 함수
  const handleSaveChanges = async () => {
    if (pendingNodes.length === 0 && pendingCategories.length === 0) {
      alert("추가된 노드나 카테고리가 없습니다.")
      return
    }

    try {
      // 📊 수정된 SVG 생성 및 로그
      console.log("=== 도면 편집 SVG 수정 ===")
      console.log("건물명:", building)
      console.log("층수:", floor)
      console.log("추가할 노드 개수:", pendingNodes.length)
      console.log("추가할 카테고리 개수:", pendingCategories.length)
      
      // 📍 노드 좌표 상세 로그
      console.log("--- 추가할 노드들 ---")
      pendingNodes.forEach((node, index) => {
        console.log(`노드 ${index + 1}:`, {
          id: node.id,
          x: node.x,
          y: node.y,
          width: node.width,
          height: node.height,
          element: node.element,
          layer: node.layer,
          nodeType: node.nodeType
        })
      })
      
      // 🏷️ 카테고리 좌표 상세 로그
      console.log("--- 추가할 카테고리들 ---")
      pendingCategories.forEach((category, index) => {
        console.log(`카테고리 ${index + 1}:`, {
          id: category.id,
          x: category.x,
          y: category.y,
          width: category.width,
          height: category.height,
          element: category.element,
          layer: category.layer,
          categoryType: category.categoryType
        })
      })

      // SVG 파일에 노드와 카테고리 추가
      const modifiedSvg = addNodesToSvg(svgRaw, pendingNodes, pendingCategories)
      
      console.log("--- 수정된 SVG 파일 검증 ---")
      console.log("SVG 내용 길이:", modifiedSvg.length, "characters")
      
      // 🔍 수정된 SVG 파일에 실제로 노드가 포함되어 있는지 확인
      if (modifiedSvg.includes('Navigation_Nodes')) {
        console.log("✅ SVG에 Navigation_Nodes 레이어가 포함되어 있습니다.")
        const nodeMatches = modifiedSvg.match(/<circle[^>]*>/g) || []
        console.log("✅ SVG에 포함된 circle 요소 개수:", nodeMatches.length)
      } else {
        console.log("❌ SVG에 Navigation_Nodes 레이어가 없습니다!")
      }
      
      if (modifiedSvg.includes('Categories')) {
        console.log("✅ SVG에 Categories 레이어가 포함되어 있습니다.")
      } else {
        console.log("❌ SVG에 Categories 레이어가 없습니다!")
      }
      
      // 수정된 SVG의 Navigation_Nodes 부분만 추출해서 확인
      const navNodesMatch = modifiedSvg.match(/<g[^>]*id="Navigation_Nodes"[^>]*>.*?<\/g>/s)
      if (navNodesMatch) {
        console.log("Navigation_Nodes 레이어 내용:", navNodesMatch[0])
      }
      
      // 수정된 SVG의 Categories 부분만 추출해서 확인
      const categoriesMatch = modifiedSvg.match(/<g[^>]*id="Categories"[^>]*>.*?<\/g>/s)
      if (categoriesMatch) {
        console.log("Categories 레이어 내용:", categoriesMatch[0])
      }

      // 📁 수정된 SVG 파일 다운로드 기능
      const downloadSvg = () => {
        const blob = new Blob([modifiedSvg], { type: 'image/svg+xml' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${building}_${floor}_modified.svg`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
      }

      // 🔍 수정된 SVG를 새 창에서 미리보기
      const previewSvg = () => {
        const newWindow = window.open('', '_blank')
        newWindow.document.write(`
          <html>
            <head>
              <title>수정된 SVG 미리보기 - ${building} ${floor}</title>
              <style>
                body { margin: 0; padding: 20px; background: #f5f5f5; }
                .preview-container { 
                  background: white; 
                  border-radius: 8px; 
                  padding: 20px; 
                  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  max-width: 1200px;
                  margin: 0 auto;
                }
                h1 { color: #333; margin-bottom: 20px; }
                .info { 
                  background: #e3f2fd; 
                  padding: 15px; 
                  border-radius: 6px; 
                  margin-bottom: 20px;
                  border-left: 4px solid #2196f3;
                }
                svg { 
                  max-width: 100%; 
                  height: auto; 
                  border: 1px solid #ddd; 
                  background: white;
                }
              </style>
            </head>
            <body>
              <div class="preview-container">
                <h1>수정된 SVG 미리보기</h1>
                <div class="info">
                  <strong>건물:</strong> ${building}<br>
                  <strong>층수:</strong> ${floor}<br>
                  <strong>추가된 노드:</strong> ${pendingNodes.length}개<br>
                  <strong>추가된 카테고리:</strong> ${pendingCategories.length}개
                </div>
                ${modifiedSvg}
              </div>
            </body>
          </html>
        `)
        newWindow.document.close()
      }

      // 사용자에게 선택 옵션 제공
      const userChoice = confirm(
        `수정이 완료되었습니다!\n\n` +
        `추가된 노드: ${pendingNodes.length}개\n` +
        `추가된 카테고리: ${pendingCategories.length}개\n\n` +
        `확인 방법을 선택하세요:\n` +
        `• 확인: 새 창에서 미리보기\n` +
        `• 취소: SVG 파일 다운로드`
      )

      if (userChoice) {
        previewSvg()
      } else {
        downloadSvg()
      }

      // 상태 초기화
      setPendingNodes([])
      setPendingCategories([])
      setNewNodeName("")
      setSelectedCategory("")
      setNodeType("stairs")
      setAutoGeneratedName("")

    } catch (error) {
      console.error("=== SVG 수정 오류 ===")
      console.error("오류 타입:", error.name)
      console.error("오류 메시지:", error.message)
      console.error("오류 스택:", error.stack)
      alert("SVG 수정 중 오류가 발생했습니다.")
    }
  }

  // SVG에 노드 추가하는 함수
  const addNodesToSvg = (svgXml, nodes, categories = []) => {
    console.log("=== SVG 노드 추가 시작 ===")
    console.log("추가할 노드 개수:", nodes.length)
    console.log("추가할 카테고리 개수:", categories.length)
    
    const parser = new DOMParser()
    const doc = parser.parseFromString(svgXml, "image/svg+xml")
    
    let navigationLayer = doc.querySelector('g[id="Navigation_Nodes"]') ||
                         doc.querySelector('g[id="navigation_nodes"]') ||
                         doc.querySelector('g[id="Navigation_nodes"]') ||
                         doc.querySelector('g[id="navigation-nodes"]')

    // Navigation_Nodes 레이어가 없으면 생성
    if (!navigationLayer) {
      console.log("Navigation_Nodes 레이어가 없어서 새로 생성합니다.")
      navigationLayer = doc.createElementNS("http://www.w3.org/2000/svg", "g")
      navigationLayer.setAttribute("id", "Navigation_Nodes")
      doc.querySelector("svg").appendChild(navigationLayer)
    } else {
      console.log("기존 Navigation_Nodes 레이어를 찾았습니다.")
    }

    // Categories 레이어 찾기
    let categoriesLayer = doc.querySelector('g[id="Categories"]') ||
                         doc.querySelector('g[id="categories"]') ||
                         doc.querySelector('g[id="Category"]') ||
                         doc.querySelector('g[id="category"]')

    // Categories 레이어가 없으면 생성
    if (!categoriesLayer) {
      console.log("Categories 레이어가 없어서 새로 생성합니다.")
      categoriesLayer = doc.createElementNS("http://www.w3.org/2000/svg", "g")
      categoriesLayer.setAttribute("id", "Categories")
      doc.querySelector("svg").appendChild(categoriesLayer)
    } else {
      console.log("기존 Categories 레이어를 찾았습니다.")
    }

    // 각 노드를 SVG 요소로 추가 (기존 노드와 동일한 스타일)
    nodes.forEach((node, index) => {
      const nodeId = node.id.split("@")[2] // building@floor@nodeId에서 nodeId만 추출
      
      console.log(`노드 ${index + 1} SVG 추가:`, {
        nodeId,
        cx: node.x,
        cy: node.y,
        r: "2.1957438"
      })
      
      const circle = doc.createElementNS("http://www.w3.org/2000/svg", "circle")
      circle.setAttribute("id", nodeId)
      circle.setAttribute("cx", node.x)
      circle.setAttribute("cy", node.y)
      circle.setAttribute("r", "2.1957438") // 기존 노드와 동일한 반지름
      circle.setAttribute("style", "fill:#00ffff;fill-opacity:0;stroke:#ffffff;stroke-width:0") // 기존 노드와 동일한 스타일
      
      navigationLayer.appendChild(circle)
    })

    // 각 카테고리를 SVG 요소로 추가 (카테고리는 투명하게 설정)
    categories.forEach((category, index) => {
      const categoryId = category.id.split("@")[2] // building@floor@categoryId에서 categoryId만 추출
      
      console.log(`카테고리 ${index + 1} SVG 추가:`, {
        categoryId,
        cx: category.x,
        cy: category.y,
        r: "2.1957438"
      })
      
      const circle = doc.createElementNS("http://www.w3.org/2000/svg", "circle")
      circle.setAttribute("id", categoryId)
      circle.setAttribute("cx", category.x)
      circle.setAttribute("cy", category.y)
      circle.setAttribute("r", "2.1957438") // 기존 노드와 동일한 반지름
      circle.setAttribute("style", "fill:#ff6b6b;fill-opacity:0;stroke:#ff6b6b;stroke-opacity:0;stroke-width:0") // 카테고리는 완전 투명하게 설정
      
      categoriesLayer.appendChild(circle)
    })

    const result = doc.documentElement.outerHTML
    
    // 🔍 SVG 수정 결과 상세 확인
    console.log("SVG 수정 완료. 최종 SVG 길이:", result.length, "characters")
    
    // Navigation_Nodes 레이어에 실제로 노드가 추가되었는지 확인
    const finalNavigationLayer = doc.querySelector('g[id="Navigation_Nodes"]')
    if (finalNavigationLayer) {
      const addedNodes = finalNavigationLayer.querySelectorAll('circle')
      console.log("Navigation_Nodes 레이어에 추가된 노드 개수:", addedNodes.length)
      addedNodes.forEach((node, index) => {
        console.log(`추가된 노드 ${index + 1}:`, {
          id: node.getAttribute('id'),
          cx: node.getAttribute('cx'),
          cy: node.getAttribute('cy'),
          r: node.getAttribute('r'),
          style: node.getAttribute('style')
        })
      })
    }
    
    // Categories 레이어에 실제로 카테고리가 추가되었는지 확인
    const finalCategoriesLayer = doc.querySelector('g[id="Categories"]')
    if (finalCategoriesLayer) {
      const addedCategories = finalCategoriesLayer.querySelectorAll('circle')
      console.log("Categories 레이어에 추가된 카테고리 개수:", addedCategories.length)
      addedCategories.forEach((category, index) => {
        console.log(`추가된 카테고리 ${index + 1}:`, {
          id: category.getAttribute('id'),
          cx: category.getAttribute('cx'),
          cy: category.getAttribute('cy'),
          r: category.getAttribute('r'),
          style: category.getAttribute('style')
        })
      })
    }
    
    // 🔍 수정된 SVG의 일부 내용 확인 (처음 500자)
    console.log("수정된 SVG 시작 부분:", result.substring(0, 500))
    console.log("=== SVG 노드 추가 완료 ===")
    
    return result
  }

  const handleAddCategory = () => {
    if (!selectedCategory) {
      alert("카테고리를 선택해주세요.")
      return
    }

    // 카테고리 추가 모드로 전환
    setIsAddingCategoryMode(true)
    setShowCategoryModal(false)
    alert("도면에서 카테고리를 추가할 위치를 클릭해주세요.")
  }

  function processSvg(svgXml) {
    const parser = new DOMParser()
    const doc = parser.parseFromString(svgXml, "image/svg+xml")
    const svgEl = doc.querySelector("svg")
    if (!svgEl) return svgXml

    const existingViewBox = svgEl.getAttribute("viewBox")
    if (existingViewBox) {
      const parts = existingViewBox.split(/[\s,]+/).map(Number)
      if (parts.length === 4) {
        setSvgViewBox({ x: parts[0], y: parts[1], width: parts[2], height: parts[3] })
        return svgXml
      }
    }

    const width = parseFloat(svgEl.getAttribute("width")) || 400
    const height = parseFloat(svgEl.getAttribute("height")) || 400
    const viewBoxStr = `0 0 ${width} ${height}`
    svgEl.setAttribute("viewBox", viewBoxStr)
    setSvgViewBox({ x: 0, y: 0, width, height })
    svgEl.removeAttribute("width")
    svgEl.removeAttribute("height")

    return doc.documentElement.outerHTML
  }

  function parseSvgNodes(svgXml, buildingName, floorName) {
    const parser = new DOMParser()
    const doc = parser.parseFromString(svgXml, "image/svg+xml")
    const nodes = []

    const navigationLayer =
      doc.querySelector('g[id="Navigation_Nodes"]') ||
      doc.querySelector('g[id="navigation_nodes"]') ||
      doc.querySelector('g[id="Navigation_nodes"]') ||
      doc.querySelector('g[id="navigation-nodes"]')

    if (!navigationLayer) {
      return []
    }

    const allElements = navigationLayer.querySelectorAll("*[id]")
    allElements.forEach((element) => {
      const nodeSuffix = element.getAttribute("id")
      if (!nodeSuffix) return
      const fullNodeId = `${buildingName}@${floorName}@${nodeSuffix}`

      let x = 0, y = 0, width = 0, height = 0
      switch (element.tagName.toLowerCase()) {
        case "rect":
          x = parseFloat(element.getAttribute("x") || 0)
          y = parseFloat(element.getAttribute("y") || 0)
          width = parseFloat(element.getAttribute("width") || 0)
          height = parseFloat(element.getAttribute("height") || 0)
          break
        case "circle":
          x = parseFloat(element.getAttribute("cx") || 0)
          y = parseFloat(element.getAttribute("cy") || 0)
          width = height = parseFloat(element.getAttribute("r") || 0) * 2
          break
        case "ellipse":
          x = parseFloat(element.getAttribute("cx") || 0)
          y = parseFloat(element.getAttribute("cy") || 0)
          width = parseFloat(element.getAttribute("rx") || 0) * 2
          height = parseFloat(element.getAttribute("ry") || 0) * 2
          break
        case "line":
          x = parseFloat(element.getAttribute("x1") || 0)
          y = parseFloat(element.getAttribute("y1") || 0)
          const x2 = parseFloat(element.getAttribute("x2") || 0)
          const y2 = parseFloat(element.getAttribute("y2") || 0)
          width = Math.abs(x2 - x)
          height = Math.abs(y2 - y)
          break
        case "polygon":
        case "polyline":
          const points = element.getAttribute("points") || ""
          const pointsArray = points.split(/[\s,]+/).filter((p) => p).map(Number)
          if (pointsArray.length >= 2) {
            const xCoords = pointsArray.filter((_, i) => i % 2 === 0)
            const yCoords = pointsArray.filter((_, i) => i % 2 === 1)
            x = Math.min(...xCoords)
            y = Math.min(...yCoords)
            width = Math.max(...xCoords) - x
            height = Math.max(...yCoords) - y
          }
          break
        case "path":
          const d = element.getAttribute("d") || ""
          const matches = d.match(/[ML]\s*([0-9.-]+)\s*,?\s*([0-9.-]+)/g)
          if (matches && matches.length > 0) {
            const coords = matches.map((m) => {
              const nums = m.replace(/[ML]\s*/, "").split(/[\s,]+/).map(Number)
              return { x: nums[0] || 0, y: nums[1] || 0 }
            })
            const xCoords = coords.map((c) => c.x)
            const yCoords = coords.map((c) => c.y)
            x = Math.min(...xCoords)
            y = Math.min(...yCoords)
            width = Math.max(...xCoords) - x
            height = Math.max(...yCoords) - y
          }
          break
        case "text":
          x = parseFloat(element.getAttribute("x") || 0)
          y = parseFloat(element.getAttribute("y") || 0)
          width = element.textContent ? element.textContent.length * 8 : 50
          height = 20
          break
        case "g":
          const transform = element.getAttribute("transform") || ""
          const translateMatch = transform.match(/translate\(([^)]+)\)/)
          if (translateMatch) {
            const translateValues = translateMatch[1].split(/[\s,]+/).map(Number)
            x = translateValues[0] || 0
            y = translateValues[1] || 0
          }
          width = height = 20
          break
        default:
          x = parseFloat(element.getAttribute("x") || 0)
          y = parseFloat(element.getAttribute("y") || 0)
          width = parseFloat(element.getAttribute("width") || 20)
          height = parseFloat(element.getAttribute("height") || 20)
      }

      nodes.push({ id: fullNodeId, x, y, width, height, element: element.tagName.toLowerCase(), layer: "Navigation_Nodes" })
    })

    return nodes
  }

  useEffect(() => {
    if (!building || !floor) return

    setLoading(true)
    setError("")

    fetch(`/api/map-route?building=${encodeURIComponent(building)}&floor=${encodeURIComponent(floor)}`)
      .then((res) => res.json())
      .then((data) => {
        const fileList = Array.isArray(data) ? data : [data]
        const rawSvgUrl = fileList[0]?.File
        const nodesInfo = fileList[0]?.nodes || {}
        let edgesInfo = fileList[0]?.edges

        if (!edgesInfo) {
          edgesInfo = []
          Object.entries(nodesInfo).forEach(([from, arr]) => {
            arr.forEach((edgeObj) => {
              const to = typeof edgeObj === "string" ? edgeObj : (edgeObj.node || edgeObj.to)
              if (to) edgesInfo.push({ from, to })
            })
          })
        }

        if (rawSvgUrl) {
          const svgUrl = rawSvgUrl + (rawSvgUrl.includes("?") ? "&" : "?") + "ts=" + Date.now()
          setSvgRaw("")
          setSvgNodes([])
          setEdges([])

          fetch(svgUrl)
            .then((res) => res.text())
            .then((svgXml) => {
              const processedSvg = processSvg(svgXml)
              setSvgRaw(processedSvg)
              setEdges(edgesInfo)
              const parsedNodes = parseSvgNodes(svgXml, building, floor)
              setSvgNodes(parsedNodes)
            })
            .catch(() => {
              setSvgRaw("")
              setSvgNodes([])
              setEdges([])
              setError("도면을 불러오지 못했습니다.")
            })
        } else {
          setSvgRaw("")
          setSvgNodes([])
          setEdges([])
          setError("해당 건물/층의 맵 파일을 찾을 수 없습니다.")
        }
      })
      .catch(() => {
        setSvgRaw("")
        setSvgNodes([])
        setEdges([])
        setError("맵 데이터를 불러오지 못했습니다.")
      })
      .finally(() => setLoading(false))
  }, [building, floor])

  return (
    <div 
      className={`${styles["room-root"]} ${styles["edit-page-root"]}`}
      style={{
        margin: 0,
        padding: 0,
        width: '100vw',
        height: '100vh',
        background: '#f4f7fc',
        overflow: 'hidden',
        position: 'fixed',
        top: 0,
        left: 0
      }}
    >
      <span className={styles["room-header"]}>도면 편집 페이지</span>
      {building && floor && (
        <div
          style={{
            width: "100%",
            fontSize: 16,
            color: "#2574f5",
            fontWeight: 600,
            marginBottom: 12,
            textAlign: "center",
            whiteSpace: "nowrap",
            overflow: "hidden",
          }}
        >
          건물명: {building} / 층수: {floor}
        </div>
      )}
      <div className={styles["room-content"]}>
        <div className={styles["room-manage-map-wrap"]} style={{ position: "relative" }}>
          {/* 툴바 */}
          <div className={styles["edit-toolbar"]}>
            <button
              onClick={() => setShowNodeModal(true)}
              className={`${styles["toolbar-btn"]} ${styles["node-btn"]}`}
              title="노드 추가"
            >
              <div className={styles["toolbar-circle"]}></div>
            </button>
            <button
              onClick={() => setShowCategoryModal(true)}
              className={`${styles["toolbar-btn"]} ${styles["category-btn"]}`}
              title="카테고리 추가"
            >
              <div className={styles["toolbar-circle"]}></div>
            </button>
          </div>
          
          <div style={{ textAlign: "right", marginBottom: "8px" }}>
            {(pendingNodes.length > 0 || pendingCategories.length > 0) && (
              <button
                onClick={handleSaveChanges}
                style={{
                  padding: "6px 14px",
                  fontSize: "14px",
                  fontWeight: "bold",
                  color: "#fff",
                  backgroundColor: "#28a745",
                  border: "none",
                  borderRadius: "6px",
                  cursor: "pointer",
                  marginRight: "8px"
                }}
              >
                수정 완료 ({pendingNodes.length}개 노드, {pendingCategories.length}개 카테고리)
              </button>
            )}
            <button
              onClick={() => router.back()}
              style={{
                padding: "6px 14px",
                fontSize: "14px",
                fontWeight: "bold",
                color: "#fff",
                backgroundColor: "#2574f5",
                border: "none",
                borderRadius: "6px",
                cursor: "pointer",
                marginRight: "8px"
              }}
            >
              뒤로가기
            </button>
          </div>
          <div
            style={{ position: "relative", width: CANVAS_WIDTH, height: CANVAS_HEIGHT, border: "1px solid #ddd", backgroundColor: "#f8f9fa", overflow: "hidden" }}
          >
            {loading && (
              <div className={styles["room-manage-canvas-placeholder"]}>맵 로딩 중...</div>
            )}
            {!loading && (!building || !floor) && (
              <div className={styles["room-manage-canvas-placeholder"]}>URL의 building/floor 파라미터가 필요합니다.</div>
            )}
            {!loading && building && floor && !svgRaw && (
              <div className={styles["room-manage-canvas-placeholder"]}>{error || "해당 건물/층의 맵 파일을 찾을 수 없습니다."}</div>
            )}

            {!loading && building && floor && svgRaw && (() => {
              const scale = Math.min(CANVAS_WIDTH / svgViewBox.width, CANVAS_HEIGHT / svgViewBox.height)
              const offsetX = (CANVAS_WIDTH - svgViewBox.width * scale) / 2
              const offsetY = (CANVAS_HEIGHT - svgViewBox.height * scale) / 2

              return (
                <div
                  ref={mapContainerRef}
                  onClick={handleMapClick}
                  style={{
                    width: svgViewBox.width,
                    height: svgViewBox.height,
                    transform: `translate(${offsetX}px, ${offsetY}px) scale(${scale})`,
                    transformOrigin: "top left",
                    position: "relative",
                    cursor: isAddingMode ? "crosshair" : "default",
                  }}
                >
                  <div
                    style={{ position: "absolute", top: 0, left: 0, width: "100%", height: "100%" }}
                    dangerouslySetInnerHTML={{ __html: svgRaw }}
                  />


                  {/* 기존 노드들 */}
                  {svgNodes.map((node, index) => (
                    <div
                      key={`node-overlay-${node.id}-${index}`}
                      style={{
                        position: "absolute",
                        left: `${node.x - node.width / 2}px`,
                        top: `${node.y - node.height / 2}px`,
                        width: `${node.width}px`,
                        height: `${node.height}px`,
                        border: "1px solid #007bff",
                        backgroundColor: "rgba(0, 123, 255, 0.08)",
                        borderRadius: 4,
                      }}
                      title={`ID: ${node.id}`}
                    />
                  ))}
                  
                  {/* 임시로 추가된 노드들 */}
                  {pendingNodes.map((node, index) => (
                    <div
                      key={`pending-node-${node.id}-${index}`}
                      style={{
                        position: "absolute",
                        left: `${node.x - node.width / 2}px`,
                        top: `${node.y - node.height / 2}px`,
                        width: `${node.width}px`,
                        height: `${node.height}px`,
                        border: "1px solid #ff6b6b",
                        backgroundColor: "rgba(255, 107, 107, 0.1)",
                        borderRadius: "50%",
                        animation: "pulse 1.5s infinite",
                      }}
                      title={`새 노드: ${node.id}`}
                    />
                  ))}

                  {/* 임시로 추가된 카테고리들 */}
                  {pendingCategories.map((category, index) => (
                    <div
                      key={`pending-category-${category.id}-${index}`}
                      style={{
                        position: "absolute",
                        left: `${category.x - category.width / 2}px`,
                        top: `${category.y - category.height / 2}px`,
                        width: `${category.width}px`,
                        height: `${category.height}px`,
                        border: "1px solid #4ecdc4",
                        backgroundColor: "rgba(78, 205, 196, 0.1)",
                        borderRadius: "50%",
                        animation: "pulse 1.5s infinite",
                      }}
                      title={`새 카테고리: ${category.id}`}
                    />
                  ))}
                </div>
              )
            })()}
          </div>
        </div>
      </div>

      {/* 노드 추가 모달 */}
      {showNodeModal && (
        <div className={styles["modal-overlay"]} onClick={() => setShowNodeModal(false)}>
          <div className={styles["node-modal-content"]} onClick={(e) => e.stopPropagation()}>
            {/* 제목 */}
            <div className={styles["node-modal-title"]}>
              <h3>노드 추가</h3>
              <div className={styles["title-underline"]}></div>
            </div>

            {/* 라디오 버튼 선택 */}
            <div className={styles["node-type-selection"]}>
              <label className={styles["radio-option"]}>
                <input
                  type="radio"
                  name="nodeType"
                  value="stairs"
                  checked={nodeType === "stairs"}
                  onChange={(e) => setNodeType(e.target.value)}
                />
                <span className={styles["radio-custom"]}></span>
                계단
              </label>
              <label className={styles["radio-option"]}>
                <input
                  type="radio"
                  name="nodeType"
                  value="normal"
                  checked={nodeType === "normal"}
                  onChange={(e) => setNodeType(e.target.value)}
                />
                <span className={styles["radio-custom"]}></span>
                노드
              </label>
            </div>

            {/* 자동 생성 노드명 표시 */}
            {nodeType === "normal" && (
              <div className={styles["auto-generated-name"]}>
                자동 생성 노드명: {autoGeneratedName}
              </div>
            )}

            {/* 입력 필드 */}
            {nodeType === "stairs" && (
              <div className={styles["input-fields"]}>
                <input
                  type="text"
                  value={newNodeName}
                  onChange={(e) => setNewNodeName(e.target.value)}
                  placeholder="노드명"
                  className={styles["name-input"]}
                />
              </div>
            )}

            {/* 액션 버튼들 */}
            <div className={styles["modal-actions"]}>
              <button
                onClick={() => setShowNodeModal(false)}
                className={styles["cancel-btn"]}
              >
                취소
              </button>
              <button
                onClick={handleAddNode}
                className={styles["save-btn"]}
              >
                저장
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 카테고리 추가 모달 */}
      {showCategoryModal && (
        <div className={styles["modal-overlay"]} onClick={() => setShowCategoryModal(false)}>
          <div className={styles["node-modal-content"]} onClick={(e) => e.stopPropagation()}>
            {/* 제목 */}
            <div className={styles["node-modal-title"]}>
              <h3>카테고리 추가</h3>
              <div className={styles["title-underline"]}></div>
            </div>

            {/* 카테고리 선택 */}
            <div className={styles["input-fields"]}>
              <select
                value={selectedCategory}
                onChange={(e) => setSelectedCategory(e.target.value)}
                className={styles["category-select"]}
              >
                <option value="">카테고리를 선택하세요</option>
                {categoryOptions.map((category) => (
                  <option key={category} value={category}>
                    {category}
                  </option>
                ))}
              </select>
            </div>

            {/* 액션 버튼들 */}
            <div className={styles["modal-actions"]}>
              <button
                onClick={() => setShowCategoryModal(false)}
                className={styles["cancel-btn"]}
              >
                취소
              </button>
              <button
                onClick={handleAddCategory}
                className={styles["save-btn"]}
              >
                저장
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
